In [2]:
import numpy as np
numbers=[1,2,3,4]
strings=['a','b','c']
np_numbers=np.array(numbers)
np_strings=np.array(strings)
print(np_numbers)
print(type(numbers))
print(type(np_numbers))
print(np_strings)
print(type(strings))
print(type(np_strings))

[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
['a' 'b' 'c']
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
np_matrix=np.array(matrix)
print(type(matrix),matrix)
print(type(np_matrix))
print(np_matrix)

<class 'list'> [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr1=np.arange(0,10)
print(arr1)
arr2=np.arange(0,10,2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [5]:
arr3=np.linspace(0,5)
print(arr3)
arr4=np.linspace(10,50,45)
print(arr4)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
[10.         10.90909091 11.81818182 12.72727273 13.63636364 14.54545455
 15.45454545 16.36363636 17.27272727 18.18181818 19.09090909 20.
 20.90909091 21.81818182 22.72727273 23.63636364 24.54545455 25.45454545
 26.36363636 27.27272727 28.18181818 29.09090909 30.         30.90909091
 31.81818182 32.72727273 33.63636364 34.54545455 35.45454545 36.36363636
 37.27272727 38.18181818 39.09090909 40.         40.90909091 41.81818182
 42.727272

In [6]:
arr5=np.zeros([3,5])
print(arr5)
arr6=np.ones([3,5])
print(arr6)
arr7=np.eye(5)
print(arr7)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
arr8=np.arange(0,15)
print(arr8)
arr8=arr8.reshape(3,5)
print(arr8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
#Sen, Cos
sin=np.sin(4) #radians
print (sin)

arr_syn=np.sin(arr8)
print(arr_syn)


-0.7568024953079282
[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]]


In [9]:
l1=np.arange(1,4)
l2=np.arange(4,7)
print(l1+l2)
print(l1-l2)
print(l1*l2)
print(l1/l2)
print(1/l1)
print(l1**l2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         0.5        0.33333333]
[  1  32 729]


In [10]:
m1=np.arange(1,10).reshape(3,3)
m2=np.eye(3)

print(m1,m2)
print(m1+m2)
print(m1-m2)
print(m1*m2)
print(m1/m2)


[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/tmp/ipykernel_12265/729529342.py:8: RuntimeWarning: divide by zero encountered in divide
  print(m1/m2)


In [11]:
m3=np.arange(1,10).reshape(3,3)
m4=np.arange(11,20).reshape(3,3)
print(m3,m4)
print('*', m3 @ m4)
print(np.transpose(m3))
print(m3.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]
* [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
print(np.min(m3))
print(np.max(m3))

random1 = np.random.rand(5)
print(random1)
random2 = np.random.rand(5,5)
print(random2)
random3 = np.random.randn(5,5)
print(random3)

print('Mean:', np.mean(random3))
print('Standard:', np.std(random3))



random4 = np.random.randint(1,10,10)
print(random4,random4>5, random4[random4>5])
random5 = np.random.randint(1,10,[5,5])
print(random5,random5[1],random5[1][1],random5[0:2,1:3])

1
9
[0.80529579 0.42831949 0.75654932 0.27173627 0.99526523]
[[0.63502285 0.52318775 0.3941948  0.28719201 0.63164843]
 [0.55865535 0.67783734 0.41884627 0.02734014 0.74694813]
 [0.03231728 0.87147604 0.63625899 0.19170984 0.60700213]
 [0.41876899 0.48071406 0.88519124 0.15029445 0.04376005]
 [0.78200284 0.459162   0.7370271  0.08887704 0.57407522]]
[[ 0.58433732 -2.24454976 -1.15275459 -1.1201205   0.23239643]
 [ 0.97607566 -0.27592675  2.54606777  0.40778286 -0.29365368]
 [-1.43659599 -0.75534462 -1.65280362 -0.59440404 -0.68316232]
 [-1.11588467 -0.91093618  0.14067292  0.80678107 -0.58305448]
 [ 1.96590453 -0.40726481  3.33714533  0.77694638 -1.15829173]]
Mean: -0.10442549880456609
Standard: 1.2944875096919282
[5 6 2 4 8 5 6 1 3 3] [False  True False False  True False  True False False False] [6 8 6]
[[9 3 3 2 7]
 [9 3 6 8 3]
 [5 1 8 5 1]
 [7 2 3 2 9]
 [1 2 2 5 9]] [9 3 6 8 3] 3 [[3 3]
 [3 6]]


In [13]:
print(random4[5])
print(random4[3:5])

5
[4 8]


In [14]:
random3
print(random3[random3>0],random3[random3<0])

[0.58433732 0.23239643 0.97607566 2.54606777 0.40778286 0.14067292
 0.80678107 1.96590453 3.33714533 0.77694638] [-2.24454976 -1.15275459 -1.1201205  -0.27592675 -0.29365368 -1.43659599
 -0.75534462 -1.65280362 -0.59440404 -0.68316232 -1.11588467 -0.91093618
 -0.58305448 -0.40726481 -1.15829173]


In [15]:
random5 = np.random.randint(1,10,[5,5])
random5[0:3,0:3]=2
sub_matrix=random5[0:3,0:3].copy()
print(random5,sub_matrix)

[[2 2 2 2 8]
 [2 2 2 2 5]
 [2 2 2 2 9]
 [3 8 2 8 2]
 [8 8 1 1 5]] [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [16]:
np.save('./random5',random5)
np.savez('./random',random4=random4,random5=random5)
r5=np.load('random5.npy')
r=np.load('random.npz')
print(r5,r['random4'],r['random5'])

[[2 2 2 2 8]
 [2 2 2 2 5]
 [2 2 2 2 9]
 [3 8 2 8 2]
 [8 8 1 1 5]] [5 6 2 4 8 5 6 1 3 3] [[2 2 2 2 8]
 [2 2 2 2 5]
 [2 2 2 2 9]
 [3 8 2 8 2]
 [8 8 1 1 5]]


In [17]:
np.savetxt('text.txt',random4,delimiter=",")
r4Text=np.loadtxt('text.txt',delimiter=",")
print(r4Text)

[5. 6. 2. 4. 8. 5. 6. 1. 3. 3.]


In [18]:
import numpy as np
import pandas as pd
import random

med_price_list = [random.randint(10, 100) for i in range(5)]
med_price_arr=np.array(med_price_list)
print(med_price_list)
print(med_price_arr)
serie_list=pd.Series(med_price_list)
serie_array=pd.Series(med_price_arr)
print(serie_list)
print(serie_array)


[14, 85, 25, 36, 17]
[14 85 25 36 17]
0    14
1    85
2    25
3    36
4    17
dtype: int64
0    14
1    85
2    25
3    36
4    17
dtype: int64


In [19]:
med_labels=['aa','bb','cc','dd','ee']
med_price_list_labels=pd.Series(med_price_list,index=med_labels)
print(med_price_list_labels)
med_price_list_updated=med_price_list_labels+2.5
print(med_price_list_updated)

aa    14
bb    85
cc    25
dd    36
ee    17
dtype: int64
aa    16.5
bb    87.5
cc    27.5
dd    38.5
ee    19.5
dtype: float64


In [20]:
students=["A","B","C","D","E"]
df1=pd.DataFrame(students,columns=['Students'])
print(df1)
grades=[1,2,3,4,5]
df2=pd.DataFrame({'Students':students,'Grades':grades})
print(df2)

  Students
0        A
1        B
2        C
3        D
4        E
  Students  Grades
0        A       1
1        B       2
2        C       3
3        D       4
4        E       5


In [21]:
dfRandom=pd.DataFrame(np.random.randn(5,2),columns=['a','b'])
print(dfRandom)

          a         b
0  1.316283 -0.443650
1  0.926558  0.408203
2 -1.956333  1.830548
3 -0.409029 -0.827963
4 -0.275454  0.344368


In [22]:
operators=['a','b','c','d']
values=[11,22,33,44]
telecom=pd.Series(values,index=operators)
print (telecom)

a    11
b    22
c    33
d    44
dtype: int64


In [23]:

print(telecom[0])
print(telecom[:2])
print(telecom[-2:])
print(telecom['b'])
print(telecom[[1,2]])
print(telecom[:'c'])
print(telecom[['c','a']])



11
a    11
b    22
dtype: int64
c    33
d    44
dtype: int64
22
b    22
c    33
dtype: int64
a    11
b    22
c    33
dtype: int64
c    33
a    11
dtype: int64


In [24]:
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1]
                           ,'total_bill':[100,75,125,50,80]})

store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [25]:
store_data[:2]

CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
1   CustID01   Boston      M  Food&Beverages         3          75

In [26]:
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [27]:
store_data[::2]

CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

In [28]:
store_data[::-1]

CustomerID       location gender            type  quantity  total_bill
4   CustID04         Austin      F          Beauty         1          80
3   CustID03  San Francisco      M        Medicine         2          50
2   CustID02        Seattle      F  Food&Beverages         4         125
1   CustID01         Boston      M  Food&Beverages         3          75
0   CustID00        Chicago      M     Electronics         1         100

In [29]:
print(store_data[:1])
print(store_data.loc[1])
print(store_data.loc[[1,4],['gender','quantity']])
print(store_data.iloc[[1,4],[0,4]])


  CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100
CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object
  gender  quantity
1      M         3
4      F         1
  CustomerID  quantity
1   CustID01         3
4   CustID04         1


In [30]:
store_data.loc[1,'location']='Bogota'
print(store_data)

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Bogota      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80


In [31]:
print(store_data['gender']=='M')
print(store_data.loc[store_data['gender']=='M'])


0     True
1     True
2    False
3     True
4    False
Name: gender, dtype: bool
  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Bogota      M  Food&Beverages         3          75
3   CustID03  San Francisco      M        Medicine         2          50


In [32]:
store_data['rating']=[1,2,3,4,5]
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Bogota      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       1  
1       2  
2       3  
3       4  
4       5

In [33]:
new_data=store_data.drop('CustomerID',axis=1)
print(store_data)
print(new_data)

  CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Bogota      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       1  
1       2  
2       3  
3       4  
4       5  
        location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       1
1         Bogota      M  Food&Beverages         3          75       2
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       5


In [34]:
store_data.drop('CustomerID',axis=1,inplace=True)

In [37]:
new_data=store_data.drop(0,axis=0)
store_data
new_data.reset_index(drop=True,inplace=True)
new_data

location gender            type  quantity  total_bill  rating
0         Bogota      M  Food&Beverages         3          75       2
1        Seattle      F  Food&Beverages         4         125       3
2  San Francisco      M        Medicine         2          50       4
3         Austin      F          Beauty         1          80       5

In [41]:
cust1 = pd.DataFrame({"customerID":['101','102','103','104'], 
                        'category': ['Medium','Medium','High','Low'],
                        'first_visit': ['yes','no','yes','yes'],
                        'sales': [123,52,214,663]},index=[0,1,2,3])

cust2 = pd.DataFrame({"customerID":['101','103','104','105'], 
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])
print(cust1)
print(cust2)

  customerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663
  customerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331


In [44]:
pd.concat([cust1,cust2],axis=0)

customerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [46]:
pd.concat([cust1,cust2],axis=1)


customerID category first_visit  sales customerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

In [48]:
#Union of
pd.merge(cust1,cust2,how='outer',on='customerID')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [50]:
#Intersection of
pd.merge(cust1,cust2,how='inner',on='customerID')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [52]:

pd.merge(cust1,cust2,how='right',on='customerID')


customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [58]:
quarters1 = pd.DataFrame({'Q1': [101,102,103],
                              'Q2': [201,202,203]},
                               index=['I0','I1','I2'])
quarters2 = pd.DataFrame({'Q3': [301,302,303],
                                  'Q4': [401,402,403]},
                               index=['I0','I2','I3'])
print(quarters1)
print(quarters2)

     Q1   Q2
I0  101  201
I1  102  202
I2  103  203
     Q3   Q4
I0  301  401
I2  302  402
I3  303  403


In [59]:
quarters1.join(quarters2,how='right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

In [63]:
dataCSV=pd.read_csv('StockData.csv')
dataCSV

stock        date    price
0     AAPL  08-02-2013  67.8542
1     AAPL  11-02-2013  68.5614
2     AAPL  12-02-2013  66.8428
3     AAPL  13-02-2013  66.7156
4     AAPL  14-02-2013  66.6556
...    ...         ...      ...
5031   ZTS  01-02-2018  77.8200
5032   ZTS  02-02-2018  76.7800
5033   ZTS  05-02-2018  73.8300
5034   ZTS  06-02-2018  73.2700
5035   ZTS  07-02-2018  73.8600

[5036 rows x 3 columns]

In [68]:
dataXLS=pd.read_excel('StockData.xlsx')
dataXLS

stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]

In [70]:
data.tail()

stock        date  price
5031   ZTS  01-02-2018  77.82
5032   ZTS  02-02-2018  76.78
5033   ZTS  05-02-2018  73.83
5034   ZTS  06-02-2018  73.27
5035   ZTS  07-02-2018  73.86

In [73]:
data.shape

(5036, 3)

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   stock   5036 non-null   object 
 1   date    5036 non-null   object 
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB


In [78]:
data['price'].min()

28.4

In [80]:
data['price'].max()


179.26

In [83]:
data['stock'].unique()

array(['AAPL', 'SNI', 'TJX', 'ZTS'], dtype=object)

In [85]:
data['stock'].value_counts()


AAPL    1259
SNI     1259
TJX     1259
ZTS     1259
Name: stock, dtype: int64

In [88]:
data['stock'].value_counts(normalize=True)


AAPL    0.25
SNI     0.25
TJX     0.25
ZTS     0.25
Name: stock, dtype: float64

In [95]:
data.groupby(['stock'])['price'].mean()

stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

In [99]:
print(data)
def margin(s):
  return s*(1.1)
data['new_column']=data['price'].apply(margin)
print(data)


     stock        date    price  new_column
0     AAPL  08-02-2013  67.8542    74.63962
1     AAPL  11-02-2013  68.5614    75.41754
2     AAPL  12-02-2013  66.8428    73.52708
3     AAPL  13-02-2013  66.7156    73.38716
4     AAPL  14-02-2013  66.6556    73.32116
...    ...         ...      ...         ...
5031   ZTS  01-02-2018  77.8200    85.60200
5032   ZTS  02-02-2018  76.7800    84.45800
5033   ZTS  05-02-2018  73.8300    81.21300
5034   ZTS  06-02-2018  73.2700    80.59700
5035   ZTS  07-02-2018  73.8600    81.24600

[5036 rows x 4 columns]
     stock        date    price  new_column
0     AAPL  08-02-2013  67.8542    74.63962
1     AAPL  11-02-2013  68.5614    75.41754
2     AAPL  12-02-2013  66.8428    73.52708
3     AAPL  13-02-2013  66.7156    73.38716
4     AAPL  14-02-2013  66.6556    73.32116
...    ...         ...      ...         ...
5031   ZTS  01-02-2018  77.8200    85.60200
5032   ZTS  02-02-2018  76.7800    84.45800
5033   ZTS  05-02-2018  73.8300    81.21300
5034   

In [105]:
data=pd.read_csv('StockData.csv')
data['date']=pd.to_datetime(data['date'],dayfirst=True)
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   stock   5036 non-null   object        
 1   date    5036 non-null   datetime64[ns]
 2   price   5036 non-null   float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 118.2+ KB


stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]

In [106]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29
